schema-version: 2.0.1

package:
  name: configurable-http-proxy

advisories:
  - id: CVE-2023-28155
    aliases:
      - GHSA-p8p7-x288-28g6
    events:
      - timestamp: 2023-11-13T19:25:22Z
        type: pending-upstream-fix
        data:
          note: cannot fix the CVE because there were no patched versions since the 'request' package is no longer supported by the maintainer
